# Generated by Django 2.1.2 on 2018-11-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_auto_20181107_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reguser',
            old_name='RegUsers_address',
            new_name='RegUser_address',
        ),
        migrations.RenameField(
            model_name='reguser',
            old_name='RegUsers_created_at',
            new_name='RegUser_created_at',
        ),
        migrations.RenameField(
            model_name='reguser',
            old_name='RegUsers_password',
            new_name='RegUser_password',
        ),
    ]
