# Generated by Django 2.1.2 on 2018-11-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20181107_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegPolicies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegPolicies_type', models.CharField(max_length=50)),
                ('RegPolicies_startdate', models.DateField()),
                ('RegPolicies_enddate', models.DateField()),
                ('RegPolicies_previouslyInsured', models.BooleanField()),
                ('RegPolicies_previouslyDamaged', models.BooleanField()),
                ('RegPolicies_Bday_YearOfProduction', models.DateField()),
                ('RegPolicies_costOfProduct', models.DecimalField(decimal_places=2, max_digits=4)),
                ('RegPolicies_description', models.CharField(max_length=50)),
            ],
        ),
    ]
