# Generated by Django 2.1.2 on 2018-11-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_regpolicies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regpolicies',
            name='RegPolicies_previouslyDamaged',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='regpolicies',
            name='RegPolicies_previouslyInsured',
            field=models.CharField(max_length=50),
        ),
    ]
