# Generated by Django 2.1.3 on 2018-11-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_auto_20181119_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regpolicies',
            name='id',
        ),
        migrations.AddField(
            model_name='regpolicies',
            name='RegPlocies_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regpolicies',
            name='RegPolicies_RegUserURL',
            field=models.ForeignKey(db_column='RegUser_id', default=1, on_delete='CASCADE', to='Backend.RegUser'),
            preserve_default=False,
        ),
    ]
