# Generated by Django 2.1.3 on 2018-11-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_auto_20181119_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regpolicies',
            name='RegPolicies_RegUserURL',
            field=models.ForeignKey(db_column='RegUser_username', on_delete='CASCADE', to='Backend.RegUser'),
        ),
    ]
