# Generated by Django 2.1.3 on 2018-11-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_auto_20181119_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regpolicies',
            name='RegPolicies_RegUserURL',
        ),
    ]
