# Generated by Django 2.1.3 on 2018-11-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_remove_regpolicies_regpolicies_reguserurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regpolicies',
            old_name='RegPlocies_id',
            new_name='RegPolicies_id',
        ),
    ]
