# Generated by Django 2.1.3 on 2018-11-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_auto_20181119_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='regpolicies',
            name='RegPolicies_username',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
