# Generated by Django 2.1.2 on 2018-12-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_auto_20181216_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reguser',
            name='RegUser_id',
        ),
        migrations.AlterField(
            model_name='reguser',
            name='RegUser_username',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
