# Generated by Django 2.1.2 on 2018-12-16 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_auto_20181216_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regpolicies',
            name='RegPolicies_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.RegUser'),
        ),
    ]
